### ISSUE TITLE
Determine if song has been found in MusicBrainz

### ISSUE THREAD

**Issue by corbs9** [tchoulihan/musicbrainz-tagger#1]
Hello!

Really like your library, it takes away the work of integrating with MusicBrainz and allows me to also make use out of your Tools class which obtains idv3 tags. 

My main problem, however, is the ability to easily identify if your library has located a track or not. To give you an example, here is my code I'm using within my application:

`Song song = Song.fetchSong(new File(filePath));
  try {
    song.getArtist();
  } catch (NullPointerException e) {
    // can't find track information in musicbrainz, let's do it another way...
    ID3v1 id3 = Tools.getId3v1Tag(new Mp3File(new File(filePath)));
}`

As you can see, I'm relying on a NullPointerException being thrown on the call to getArtist() to determine if you've found a song or not. 

May I request an addition? Could you either not create an instance of song and returning null, throwing a SongNotFoundException or providing a "isFound()" method which returns a boolean? If you're happy to, I could do the development and create a pull request?

Thanks!

**Comment by tchoulihan** [comment]
Sure, I'll create a SongNotFoundException for this.

**Comment by tchoulihan** [comment]
Okay, I added both: either way works, but the first is preferred. 

```java
song = Song.fetchSong(Tools.SAMPLE_SONG_2);

if (song.isFound()) {
  song.getArtist();
}
```

```java
try {
   song = Song.fetchSong(Tools.SAMPLE_SONG_2);
   song.getRelease();

   fail( "My method didn't throw when I expected it to" );
} catch(SongNotFoundException e) {}
```
The maven version now is `1.3.1`.

**Comment by corbs9** [comment]
Great thanks! I can't seem to find it on Maven at the moment so I can test the new functionality. Checking the source code and it looks good! The first is my preferred method, too.
